# .readthedocs.yaml

version: 2

# Set the OS, Python version and other tools
build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  apt_packages:
    - graphviz

# Tell Sphinx where to find the configuration
sphinx:
  configuration: docs/source/conf.py

# Define the Python requirements for building the docs
python:
  install:
    - requirements: docs/requirements.txt
